spring.application.name=LogiTrack Backend

# Datasource
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/logitrack?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:campus2023}
spring.datasource.password=${DB_PASSWORD:campus2023}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=${JWT_SECRET:YXZlcnRpZG8tbG9naXRyYWNrLXNlY3JldC1rZXk=}
jwt.expiration-ms=${JWT_EXPIRATION:3600000}
